# Generated by Django 3.2.9 on 2021-11-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_shared', '0001_initial'),
        ('attendance_tenant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stores',
            new_name='Store',
        ),
    ]
