# Generated by Django 3.2.9 on 2021-11-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('branch_id', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('store_mobile', models.IntegerField()),
                ('store_unique_id', models.IntegerField()),
                ('org_id', models.IntegerField()),
            ],
        ),
    ]
