# Generated by Django 3.2.9 on 2021-11-21 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='store_mobile',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
