# Generated by Django 3.2.9 on 2021-11-21 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_shared', '0002_alter_stores_store_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_id', models.IntegerField()),
                ('Employee_name', models.CharField(max_length=255)),
                ('Employee_Designation', models.CharField(max_length=255)),
                ('Employee_mob', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Salary', models.IntegerField()),
                ('Employee_DOB', models.DateField(max_length=8)),
                ('image_file', models.ImageField(upload_to='images')),
                ('Id_Proof', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_id', models.IntegerField()),
                ('Player_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player_id', models.IntegerField()),
                ('Player_name', models.CharField(max_length=255)),
                ('Player_mob', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('City', models.CharField(max_length=255)),
                ('Player_DOB', models.DateField(max_length=8)),
                ('image_file', models.ImageField(upload_to='images')),
                ('Id_Proof', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Player_games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_id', models.IntegerField()),
                ('Player_id', models.CharField(max_length=255)),
                ('Game_name', models.CharField(max_length=255)),
                ('Transaction_Type', models.CharField(choices=[('Bonus-Cash', 'Bonus-Cash'), ('Cash-IN', 'Cash-IN'), ('Cash-Out', 'Cash-Out')], max_length=20)),
                ('Cash_Out_Receipt', models.ImageField(upload_to='images')),
                ('Machine_Id', models.IntegerField()),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_user_id', models.IntegerField()),
                ('store_user_name', models.CharField(max_length=255)),
                ('store_user_pwd', models.CharField(max_length=255)),
                ('org_id', models.IntegerField()),
                ('store_id', models.IntegerField()),
            ],
        ),
    ]
